import random

first_names = [
"Marie", "Pierre", "François", "Jean", "Louis", "Antoine", "Jacques", "Guillaume", "Nicolas", "Claude", "Étienne", "Joseph", "Michel", "André", "Jean-Pierre", "Charles", "Gabriel", "Pascal", "Pierre-Jean", "Vincent", "Paul", "Jean-Baptiste", "Marc", "René", "Adrien", "Auguste", "Sébastien", "Alexandre", "Théodore", "Félix", "Honoré", "Victor", "Olivier", "Philippe", "Maxime", "Romain", "Benoît", "Emmanuel", "Louis-Antoine", "Simon", "Jules", "Georges", "Gaspard", "François-Xavier", "Célestin", "César", "Anatole", "Gustave", "Augustin", "Léon", "Claudius", "Julien", "Aimé", "Sylvain", "Grégoire", "Gilles", "Cyrille", "Amédée", "Théophile", "Émile", "Isidore", "Lucien", "Florian", "Constant", "Maximilien", "Denis", "Évariste", "Ferdinand", "Alphonse", "Guillaume-Henri", "Antonin", "Gérard", "Maurice", "Rodolphe", "Timothée", "Octave", "Eugène", "Félicien", "Baptiste", "Léandre", "Rémi", "Joséphine", "Marguerite", "Élisabeth", "Marie-Louise", "Émilie", "Catherine", "Madeleine", "Julienne", "Rose", "Adèle", "Angélique", "Eugénie", "Hélène", "Mathilde", "Louise", "Henriette", "Lucie", "Pauline", "Sophie", "Victoire", "Zéphyrine", "Caroline", "Fanny", "Irène", "Valérie"
]

last_names = ['Marie', 'Dupont', 'Pierre', 'Martin', 'François', 'Leclerc', 'Jean', 'Dubois', 'Louis', 'Lambert', 'Antoine', 'Laurent', 'Jacques', 'Girard', 'Guillaume', 'Rousseau', 'Nicolas', 'Lefebvre', 'Claude', 'Moreau', 'Étienne', 'Gauthier', 'Joseph', 'Petit', 'Michel', 'Faure', 'André', 'Dupuis', 'Jean-Pierre', 'Bernard', 'Charles', 'Leroy', 'Gabriel', 'Richard', 'Pascal', 'Simon', 'Pierre-Jean', 'Roussel', 'Vincent', 'Marchand', 'Paul', 'Robin', 'Jean-Baptiste', 'Morin', 'Marc', 'Thierry', 'René', 'Gérard', 'Adrien', 'Dubois', 'Auguste', 'Lambert', 'Sébastien', 'Deschamps', 'Alexandre', 'Renault', 'Théodore', 'Dupré', 'Félix', 'Dumont', 'Honoré', 'Morel', 'Victor', 'Henry', 'Olivier', 'Lemoine', 'Philippe', 'Roy', 'Maxime', 'Noel', 'Romain', 'Lefevre', 'Benoît', 'Mercier', 'Emmanuel', 'Giraud', 'Louis-Antoine', 'Dupont', 'Simon', 'Lambert', 'Jules', 'Bonnet', 'Georges', 'Girard', 'Gaspard', 'Lefebvre', 'François-Xavier', 'Durand', 'Célestin', 'Roussel', 'César', 'Michel', 'Anatole', 'Dupuis', 'Gustave', 'Bernard', 'Augustin', 'Leroux', 'Léon', 'Denis', 'Claudius', 'Faure', 'Julien', 'Martin', 'Aimé', 'Lambert', 'Sylvain', 'Roussel', 'Grégoire', 'Moreau', 'Gilles', 'Simon', 'Cyrille', 'Laurent', 'Amédée', 'Gauthier', 'Théophile', 'Rousseau', 'Émile', 'Richard', 'Isidore', 'Dupré', 'Lucien', 'Morel', 'Florian', 'Henry', 'Constant', 'Noel', 'Maximilien', 'Gérard', 'Denis', 'Durand', 'Évariste', 'Bonnet', 'Ferdinand', 'Giraud', 'Alphonse', 'Dupont', 'Guillaume-Henri', 'Martin', 'Antonin', 'Leroy', 'Gérard', 'Renault', 'Maurice', 'Lefevre', 'Rodolphe', 'Mercier', 'Timothée', 'Dupuis', 'Octave', 'Lambert', 'Eugène', 'Moreau', 'Félicien', 'Simon', 'Baptiste', 'Lemoine', 'Léandre', 'Gauthier', 'Rémi', 'Rousseau', 'Joséphine', 'Martin', 'Marguerite', 'Dupont', 'Élisabeth', 'Bernard', 'Marie-Louise', 'Leroy', 'Émilie', 'Girard', 'Catherine', 'Lefebvre', 'Madeleine', 'Roussel', 'Julienne', 'Noel', 'Rose', 'Lambert', 'Adèle', 'Moreau', 'Angélique', 'Simon', 'Eugénie', 'Dupré', 'Hélène', 'Henry', 'Mathilde', 'Noel', 'Louise', 'Gérard', 'Henriette', 'Dupont', 'Lucie', 'Martin', 'Pauline', 'Lefevre', 'Sophie', 'Renault']



